<a href="https://colab.research.google.com/github/gileskd/AdvancedPythonWeek4/blob/main/Giles_Week_1_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ### Student Name

Kelly Giles

## Submitting your homework!

Two steps are required for this week's homework once you have completed it:

- __Share__ this notebook with _libraryjuicepresspython@gmail.com_ so it can be marked in Colab
- __Print as PDF__ and upload to the the week's homework submission location on the Library Juice Academy LMS

# Advanced Python - Week 1 Homework

(Be sure to save this to Drive before starting)

For this week we are going to practice requesting information from an API and manipulating it as JSON and as a Dataframe.

We are going to keep working with Collection Builder. Head over to the [Collection Builder Example Projects](https://collectionbuilder.github.io/cb-examples/browse.html) listing and find a site that interests you. Spend some time browsing the website to get acquainted with its contents before proceeding with the questions.

In [ ]:
#The Libraries we will need
import requests
import json
import pandas as pd
from random import randrange

In [ ]:
# @markdown **H1** Find the URL of for the  _metadata.json_ of your selected site and paste it in here.
json_cb_url = "https://lsis5425-fall2023.github.io/group-4/assets/data/metadata.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_url)
#all of the data from the sites
total_cb_data = response_cb.json()
#just the 'objects' indexed in the site
objects_cb_data = total_cb_data['objects']
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

**H2** Run the 'show random cell' a few times to get a sense of what kind of data is in your chosen site.

In [ ]:
#Run this a few times to see random entries in the JSON data that you retrieved.
random_entry = randrange(len(objects_cb_data))
print(json.dumps(objects_cb_data[random_entry],indent=2))

{
  "title": "The House with Chicken Legs",
  "creator": "Sophie Anderson",
  "date": "2020",
  "description": "All 12-year-old Marinka wants is a friend. A real friend. Not like her house with chicken legs. Sure, the house can play games like tag and hide-and-seek, but Marinka longs for a human companion. Someone she can talk to and share secrets with.<br>But that's tough when your grandmother is a Yaga, a guardian who guides the dead into the afterlife. It's even harder when you live in a house that wanders all over the world . . . carrying you with it. Even worse, Marinka is being trained to be a Yaga. That means no school, no parties--and no playmates that stick around for more than a day.<br>So when Marinka stumbles across the chance to make a real friend, she breaks all the rules . . . with devastating consequences. Her beloved grandmother mysteriously disappears, and it's up to Marinka to find her--even if it means making a dangerous journey to the afterlife.",
  "subject": "Responsibility; Friendship; Courage",
  "location": "Russia",
  "latitude": "62.82280824575507",
  "longitude": "96.02005897624204",
  "format": "image/jpeg",
  "reference_url": "https://lsis5425-fall2023.github.io/group-4/item.html?id=coll004"
}

## Different Fields!

You can create any number of datafields and correpsonding values for those fields with a Collection Builder site. So the results from the output from the cell above will probably have wildly different results from [my site](https://elibtronic.github.io/AIL_Database/data.html) that we worked on in the Workalong notebook.


You can see all of these options from grabbing the _facets.json_ URL from a collection builder homepage. Find that URL for your selected site for **H3**

In [ ]:
# @markdown **H3** Find the URL of the facets.json for your selected site and paste it in here.
json_cb_facets_url = "https://lsis5425-fall2023.github.io/group-4/assets/data/facets.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_facets_url)
#all of the data from the sites
total_facet_data = response_cb.json()
#just the 'objects' indexed in the site
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

Run the cell below to see what the facets used for this site:

In [ ]:
print(json.dumps(total_facet_data,indent=2))

{
  "facets": [
    {
      "field": "subject",
      "terms": {
        "adventure": 2,
        "awareness": 1,
        "coming of age": 5,
        "compassion": 1,
        "courage": 5,
        "faith": 2,
        "family": 1,
        "fate": 1,
        "friendship": 4,
        "good vs. evil": 3,
        "greed": 1,
        "honesty": 1,
        "kindness": 2,
        "love": 3,
        "morality": 1,
        "overcoming adversity": 1,
        "perseverance": 1,
        "responsibility": 1,
        "self-love": 1,
        "temptation": 1,
        "truth": 1,
        "understanding": 1,
        "wisdom": 1
      }
    },
    {
      "field": "creator",
      "terms": {
        "ai-ling louie": 1,
        "amedeus mtui": 1,
        "bali rai": 1,
        "buchi offodile": 1,
        "diana wynne jones": 1,
        "grace lin": 1,
        "hans christian andersen": 1,
        "james stephens": 1,
        "jon scieszka": 1,
        "marika mccoola": 1,
        "merrie haskell": 1,
        "neil gaiman": 1,
        "robert d. san souci": 1,
        "sophie anderson": 1,
        "tracey baptiste": 1
      }
    },
    {
      "field": "format",
      "terms": {
        "image/jpeg": 15
      }
    }
  ]
}

**H3** Try to read the JSON that is displayed to the screen. What possible facets are there in the the data. Fill them in the markdown list in the cell below. Add as many entries as you need to describe the site

Facets in my site are:
- **subject:** adventure, awareness, coming of age, compassion, courage, faith, family, fate, friendship, good vs. evil, greed, honesty, kindness, love, morality, overcoming adversity, perseverance, responsibility, self-love, temptation, truth, understanding, wisdom
- **creator:** ai-ling louie, amedeus mtui, bali rai, buchi offodile, diana wynne jones, grace lin, hans christian andersen, james stephens, jon scieszka, marika mccoola, merrie haskell, neil gaiman, robert d. san souci, sophie anderson, tracey baptiste
- **format:** image/jpeg

**H4** Which facet shows up the most for your selected site? Put your answer in the cell below

This facet that shows up the most is image/jpeg it is used 15 times on my selected site.

**H5** Turn the site _metadata.json_ data into a dataframe by completing the cell below. Part of it is written for you. You just need to modify line 4.

In [ ]:
#H5

cb_data = pd.read_json(json_cb_url)
cb_normalized = pd.json_normalize(cb_data['objects'])
cb_normalized

,title,creator,date,description,subject,location,latitude,longitude,format,reference_url
0,The Jumbies,Tracey Baptiste,2016,Corinne La Mer claims she isn’t afraid of anyt...,Courage; Friendship; Coming of Age,Trinidad and Tobago,10.387973081373413,-61.25748992310327,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
1,Hansel & Gretel,Neil Gaiman,2014,"""If this isn't the definitive edition of Hanse...",Greed; Family; Temptation,Germany,50.910160669298435,10.023374909019847,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
2,Irish Fairy Tales,James Stephens,1905,James Stephens' collection of Irish Fairy Tale...,Love; Kindness; Coming of Age; Courage,Ireland,53.00128252743384,-8.043818432943647,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
3,The House with Chicken Legs,Sophie Anderson,2020,All 12-year-old Marinka wants is a friend. A r...,Responsibility; Friendship; Courage,Russia,62.82280824575507,96.02005897624204,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
4,Howl's Moving Castle,Diana Wynne Jones,2008,This entrancing classic fantasy novel is fille...,Compassion; Adventure; Love,England,52.3356853215622,-1.3013239071200993,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
5,Baba Yaga's Assistant,Marika McCoola,2015,Most children think twice before braving a hau...,Courage; Coming of Age,Russia,62.82280824575507,96.02005897624204,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
6,Where the Mountain Meets the Moon,Grace Lin,2019,"In the valley of Fruitless mountain, a young g...",Faith; Friendship,China,34.75442461422868,103.62011848474448,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
7,Tales from India,Bali Rai,2017,A collection of 20 stories from India's rich f...,Wisdom; Adventure; Morality,India,21.913270490072758,78.46830117736761,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
8,The Princess Curse,Merrie Haskell,2013,"In the fifteenth-century kingdom of Sylvania, ...",Courage; Coming of Age,France,46.49291945076635,2.376925930552558,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
9,Cendrillon: A Carribean Cinderella,Robert D. San Souci,2002,You may think you already know this story abou...,Overcoming Adversity; Coming of Age,Martinique,14.651739491935894,-61.00326423380922,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
10,The Little Mermaid,Hans Christian Andersen,1837,A mermaid princess saves a man from drowning. ...,Self-love; Good vs. Evil,Denmark,55.443940706330785,10.131176550422168,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
11,"The Lion, the Hyena, and the Rabbit",Amedeus Mtui,2015,A cunning hyena starts a few problems for form...,Honesty; Friendship; Awareness,Tanzania,-6.385140868097011,35.09878154124035,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
12,The Orphan Girl and Other Stories: West Africa...,Buchi Offodile,2001,The Orphan Girl is an Igbo story of a cruel st...,Fate; Good vs. Evil; Perseverance,Nigeria; Mauritania; Mali; Burkina Faso; Camer...,9.59484302852346,7.742839564483962,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
13,Yeh-Shen: A Cinderella Story from China,Ai-Ling Louie,1996,Scholars have deemed Yeh-Shen the oldest versi...,Kindness; Faith; Good vs. Evil; Love; Understa...,China,34.75442461422868,103.62011848474448,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
14,The True Story of the 3 Little Pigs!,Jon Scieszka,1996,“In this hysterical and clever fracture fairy ...,Truth,England,52.3356853215622,-1.3013239071200993,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...

In [ ]:
#Run this a few times to see random entries in your dataframe
cb_normalized.sample(10)

,title,creator,date,description,subject,location,latitude,longitude,format,reference_url
11,"The Lion, the Hyena, and the Rabbit",Amedeus Mtui,2015,A cunning hyena starts a few problems for form...,Honesty; Friendship; Awareness,Tanzania,-6.385140868097011,35.09878154124035,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
14,The True Story of the 3 Little Pigs!,Jon Scieszka,1996,“In this hysterical and clever fracture fairy ...,Truth,England,52.3356853215622,-1.3013239071200993,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
0,The Jumbies,Tracey Baptiste,2016,Corinne La Mer claims she isn’t afraid of anyt...,Courage; Friendship; Coming of Age,Trinidad and Tobago,10.387973081373413,-61.25748992310327,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
12,The Orphan Girl and Other Stories: West Africa...,Buchi Offodile,2001,The Orphan Girl is an Igbo story of a cruel st...,Fate; Good vs. Evil; Perseverance,Nigeria; Mauritania; Mali; Burkina Faso; Camer...,9.59484302852346,7.742839564483962,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
3,The House with Chicken Legs,Sophie Anderson,2020,All 12-year-old Marinka wants is a friend. A r...,Responsibility; Friendship; Courage,Russia,62.82280824575507,96.02005897624204,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
9,Cendrillon: A Carribean Cinderella,Robert D. San Souci,2002,You may think you already know this story abou...,Overcoming Adversity; Coming of Age,Martinique,14.651739491935894,-61.00326423380922,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
4,Howl's Moving Castle,Diana Wynne Jones,2008,This entrancing classic fantasy novel is fille...,Compassion; Adventure; Love,England,52.3356853215622,-1.3013239071200993,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
7,Tales from India,Bali Rai,2017,A collection of 20 stories from India's rich f...,Wisdom; Adventure; Morality,India,21.913270490072758,78.46830117736761,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
10,The Little Mermaid,Hans Christian Andersen,1837,A mermaid princess saves a man from drowning. ...,Self-love; Good vs. Evil,Denmark,55.443940706330785,10.131176550422168,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...
2,Irish Fairy Tales,James Stephens,1905,James Stephens' collection of Irish Fairy Tale...,Love; Kindness; Coming of Age; Courage,Ireland,53.00128252743384,-8.043818432943647,image/jpeg,https://lsis5425-fall2023.github.io/group-4/it...

**H6** This is for bonus!
Try to write a pandas statement that will display your answer from **H4**. There are plenty of ways to do this, so feel free to use your imagination. What I have started for you here might not work, so feel free to change it as needed.

In [ ]:
#Start code provided:
#cb_normalized[cb_normalized[""] == ""].count()

#This code would check which for "image/jpeg" in the "format" column, and return a table showing all of the column headings
#and the number of rows in each column where the "format" column contained "image/jpeg":
#cb_normalized[cb_normalized["format"] == "image/jpeg"].count()

#This code would perform the same check as above, but return only the count for the "format" column.
#(I got help with this from Microsoft Copilot.)
#cb_normalized[cb_normalized["format"] == "image/jpeg"].count()["format"]

#This code creates a variable named "most_facet". It checks how many times "image/jpeg" appears in the "format" column (as above),
#and makes that the value of "most_facet".
most_facet = cb_normalized[cb_normalized["format"] == "image/jpeg"].count()["format"]

print("The facet term that shows up the most is image/jpeg, it is used " + str(most_facet) + " times on my selected site.")

The facet term that shows up the most is image/jpeg, it is used 15 times on my selected site.


## All Done!

Congrats you are finished with this week's work. First save as PDF so that you can upload to the Course site then click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work.