<a href="https://colab.research.google.com/github/gileskd/AdvancedPythonWeek4/blob/main/Giles_Week_2_Workalong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Week 2 - Manipulating Structured Data

(Be sure to Copy to Drive first)

This will build on content introduced in week 1. In week 1 we learned that information can be presented on the web in HTML (ie, with formatting and graphics) or as data that can be read programmatically via Python through an _API_ (Application Program Interface).

This week we will build on what we learned by creating a dataset from a few different APIs.

# CrossRef

CrossRef is one of the organizations that product DOIs. These are the unique serial numbers that get added to published works. I think the biggest advantage to DOIs is that they allow us to get to full text of items even when URLs change for publisher websites. The other great thing is that CrossRef provides a bunch of other metadata alongside the URL to the full-text.

We'll grab information from the CrossRef API using a Python library called [crossrefapi](https://github.com/fabiobatalha/crossrefapi)


## CrossRef via the Web

Head over to the [web search](https://search.crossref.org/) for CrossRef and experiment with some searches. You'll see that there is a lot of different fields in the data.


# CrossRef via an API

We can interact with CrossRef via an API as well. This will just return data in a way that can be treated like a JSON variable.


# One item two way

To really highlight the difference between the web view and the API check out these two links for a piece I wrote about data analysis:

- [https://api.crossref.org/works/10.5334/johd.109](https://api.crossref.org/works/10.5334/johd.109)


- [https://doi.org/10.5334/johd.109](https://doi.org/10.5334/johd.109)

Click through on both to see what happens

# CrossRef via API and Python

In order to make working with the API more manageable we'll use a Python library called [crossrefapi](https://github.com/fabiobatalha/crossrefapi) that will allow us to use Python variables instead of manipulating JSON directly. Since this library is not part of the usual Python deployment we will need to install it specifically. Details about installing libraries are in the week 3 warmup activity in case you are curious

When you first run this code cell it might ask you to 'Restart' by clicking a button. Please do that, and re-run the cell. This types of things sometimes happen when you start including new libraries in the Colab environment.

In [1]:
#install the library
!pip install crossrefapi


#Load in our other usual libraries
import pandas as pd
from google.colab import drive
import numpy as np

print("Ready to proceed!")

Requirement already satisfied: crossrefapi in /usr/local/lib/python3.13/dist-packages (1.7.0)
Requirement already satisfied: ipython<9.0.0,>=8.28.0 in /usr/local/lib/python3.13/dist-packages (from crossrefapi) (8.39.0)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.13/dist-packages (from crossrefapi) (2.32.4)
Requirement already satisfied: urllib3<3.0.0,>=2.2.3 in /usr/local/lib/python3.13/dist-packages (from crossrefapi) (2.5.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.13/dist-packages (from ipython<9.0.0,>=8.28.0->crossrefapi) (4.4.2)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.13/dist-packages (from ipython<9.0.0,>=8.28.0->crossrefapi) (0.20.1)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.13/dist-packages (from ipython<9.0.0,>=8.28.0->crossrefapi) (0.2.2)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.13/dist-packages (from ipython<9.0.0,>=8.28.0->crossrefapi) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.13/dist-packages (from ipython<9.0.0,>=8.28.0->crossrefapi) (3.0.53)
Requirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.13/dist-packages (from ipython<9.0.0,>=8.28.0->crossrefapi) (2.21.0)
Requirement already satisfied: stack_data in /usr/local/lib/python3.13/dist-packages (from ipython<9.0.0,>=8.28.0->crossrefapi) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /usr/local/lib/python3.13/dist-packages (from ipython<9.0.0,>=8.28.0->crossrefapi) (5.16.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.32.3->crossrefapi) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.32.3->crossrefapi) (3.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.32.3->crossrefapi) (2026.7.22)
Requirement already satisfied: parso<0.9.0,>=0.8.7 in /usr/local/lib/python3.13/dist-packages (from jedi>=0.16->ipython<9.0.0,>=8.28.0->crossrefapi) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.13/dist-packages (from pexpect>4.3->ipython<9.0.0,>=8.28.0->crossrefapi) (0.7.0)
Requirement already satisfied: wcwidth>=0.1.4 in /usr/local/lib/python3.13/dist-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython<9.0.0,>=8.28.0->crossrefapi) (0.9.2)
Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from stack_data->ipython<9.0.0,>=8.28.0->crossrefapi) (2.3.0)
Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from stack_data->ipython<9.0.0,>=8.28.0->crossrefapi) (3.0.2)
Requirement already satisfied: pure-eval in /usr/local/lib/python3.13/dist-packages (from stack_data->ipython<9.0.0,>=8.28.0->crossrefapi) (0.2.4)
Ready to proceed!

With the library installed we will now query the API to look at the same article we saw above.

In [2]:
from crossref.restful import Works
works = Works()
item = works.doi("10.5334/johd.109")

Run the next cell to see how the information looks a lot like JSON.

In [3]:
item

{'indexed': {'date-parts': [[2025, 10, 27]],
  'date-time': '2025-10-27T08:05:33Z',
  'timestamp': 1761552333631,
  'version': 'build-2065373602'},
 'reference-count': 8,
 'publisher': 'Ubiquity Press, Ltd.',
 'content-domain': {'domain': [], 'crossmark-restriction': False},
 'short-container-title': [],
 'published-print': {'date-parts': [[2023, 6, 29]]},
 'DOI': '10.5334/johd.109',
 'type': 'journal-article',
 'created': {'date-parts': [[2023, 6, 29]],
  'date-time': '2023-06-29T06:38:10Z',
  'timestamp': 1688020690000},
 'source': 'Crossref',
 'is-referenced-by-count': 0,
 'title': ['A Mixed Method Twitter Methodology and Anonymous Corpus'],
 'prefix': '10.5334',
 'volume': '9',
 'author': [{'ORCID': 'https://orcid.org/0000-0001-9229-8569',
   'authenticated-orcid': False,
   'given': 'Tim',
   'family': 'Ribaric',
   'sequence': 'first',
   'affiliation': [],
   'role': [{'role': 'author', 'vocabulary': 'crossref'}]}],
 'member': '3285',
 'reference': [{'volume-title': 'Libraries as dysfunctional organizations and workplaces',
   'year': '2022',
   'key': 'key20230629063807_B1'},
  {'key': 'key20230629063807_B2',
   'unstructured': 'Ettarh, F. (2018). Vocational Awe and Librarianship: The Lies We Tell Ourselves – In the Library with the Lead Pipe. Retrieved from https://www.inthelibrarywiththeleadpipe.org/2018/vocational-awe/ (last accessed: April 28, 2023).'},
  {'year': '2014',
   'key': 'key20230629063807_B3',
   'article-title': 'VADER: A Parsimonious Rule-Based Model for Sentiment Analysis of Social Media Text [Full Paper]'},
  {'key': 'key20230629063807_B4',
   'unstructured': '@lis_grievances bot. (n.d.). LIS Grievances—About. Retrieved from https://lisgrievances.com/about.html (last accessed: April 17, 2023).'},
  {'key': 'key20230629063807_B5',
   'unstructured': 'Ribaric, T. (2022a). LIS Grievances. Retrieved from https://github.com/elibtronic/lis_grievances (last accessed: April 28, 2023).'},
  {'key': 'key20230629063807_B6',
   'first-page': '167',
   'volume-title': 'Libraries as Dysfunctional Organizations and Workplaces',
   'year': '2022',
   'edition': '1st ed.'},
  {'key': 'key20230629063807_B7',
   'unstructured': 'Roesslein, J. (2020). Tweepy: Twitter for Python. Retrieved from https://Github.Com/Tweepy/Tweepy (last accessed: April 28, 2023).'},
  {'key': 'key20230629063807_B8',
   'first-page': '1',
   'article-title': 'New Librarians and the Practice of Everyday Life',
   'volume': '5',
   'year': '2019',
   'journal-title': 'Canadian Journal of Academic Librarianship'}],
 'container-title': ['Journal of Open Humanities Data'],
 'original-title': [],
 'language': 'en',
 'link': [{'URL': 'https://storage.googleapis.com/jnl-up-j-johd-files/journals/1/articles/109/649d5d95b2c52.pdf',
   'content-type': 'unspecified',
   'content-version': 'vor',
   'intended-application': 'similarity-checking'}],
 'deposited': {'date-parts': [[2025, 10, 27]],
  'date-time': '2025-10-27T07:55:18Z',
  'timestamp': 1761551718000},
 'score': 1,
 'resource': {'primary': {'URL': 'http://openhumanitiesdata.metajnl.com/articles/10.5334/johd.109/'}},
 'subtitle': [],
 'short-title': [],
 'issued': {'date-parts': [[2023]]},
 'references-count': 8,
 'alternative-id': ['10.5334/johd.109'],
 'URL': 'https://doi.org/10.5334/johd.109',
 'relation': {},
 'ISSN': ['2059-481X'],
 'issn-type': [{'type': 'print', 'value': '2059-481X'}],
 'subject': [],
 'published': {'date-parts': [[2023]]},
 'article-number': '8'}


# Parts of the data

By doing a key lookup, we can find the associated value

In [4]:
item['title']

['A Mixed Method Twitter Methodology and Anonymous Corpus']

**Q1** Print the ISSN that the article is from

In [5]:
#Q1
item['ISSN']

['2059-481X']

**Q2** Print the number of references this article has

In [6]:
#Q2
item['references-count']

8

**Q3** Print the volume that this article is from

In [7]:
#Q3
item['volume']

'9'

# A more complex part of the data

Sometime we can use a key to get a value that is actually a more complex thing, like a list.

Check out this example of the author information.

In [8]:
item['author']

[{'ORCID': 'https://orcid.org/0000-0001-9229-8569',
  'authenticated-orcid': False,
  'given': 'Tim',
  'family': 'Ribaric',
  'sequence': 'first',
  'affiliation': [],
  'role': [{'role': 'author', 'vocabulary': 'crossref'}]}]


# Two levels deep

For example we can find the `family` name of the author with something like the following

In [9]:
#We are interested in the first item in this list
#which is why we index at 0
#if this piece had more than 1 author the list above
#would be bigger
author_info = item['author'][0]
author_info['family']

'Ribaric'

**Q4** Print the ORCID for this author

In [10]:
author_info = item['author'][0]
author_info['ORCID']

'https://orcid.org/0000-0001-9229-8569'

**Q5** Print the list of references this article has. You just need to modify line 1.

In [11]:
references = item['reference']

for reference in references:
  #Even more JSON objects!
  print(reference)

{'volume-title': 'Libraries as dysfunctional organizations and workplaces', 'year': '2022', 'key': 'key20230629063807_B1'}
{'key': 'key20230629063807_B2', 'unstructured': 'Ettarh, F. (2018). Vocational Awe and Librarianship: The Lies We Tell Ourselves – In the Library with the Lead Pipe. Retrieved from https://www.inthelibrarywiththeleadpipe.org/2018/vocational-awe/ (last accessed: April 28, 2023).'}
{'year': '2014', 'key': 'key20230629063807_B3', 'article-title': 'VADER: A Parsimonious Rule-Based Model for Sentiment Analysis of Social Media Text [Full Paper]'}
{'key': 'key20230629063807_B4', 'unstructured': '@lis_grievances bot. (n.d.). LIS Grievances—About. Retrieved from https://lisgrievances.com/about.html (last accessed: April 17, 2023).'}
{'key': 'key20230629063807_B5', 'unstructured': 'Ribaric, T. (2022a). LIS Grievances. Retrieved from https://github.com/elibtronic/lis_grievances (last accessed: April 28, 2023).'}
{'key': 'key20230629063807_B6', 'first-page': '167', 'volume-title': 'Libraries as Dysfunctional Organizations and Workplaces', 'year': '2022', 'edition': '1st ed.'}
{'key': 'key20230629063807_B7', 'unstructured': 'Roesslein, J. (2020). Tweepy: Twitter for Python. Retrieved from https://Github.Com/Tweepy/Tweepy (last accessed: April 28, 2023).'}
{'key': 'key20230629063807_B8', 'first-page': '1', 'article-title': 'New Librarians and the Practice of Everyday Life', 'volume': '5', 'year': '2019', 'journal-title': 'Canadian Journal of Academic Librarianship'}


# Two steps

We are now going to try a search in the CrossRef API, find some journal articles and identify the ORCIDs of the authors. We are then going to beef up this information with the ORCID API.


# Searching the API

We'll search the API based on a search query that we specify in our next cell.

In [12]:
#Original search string:
#search_string = "ACRL Competencies and student success"

#My search string:
search_string = "escape rooms in libraries"

In [13]:
search_results = works.query(bibliographic=search_string)

#We can see what actual URL of that we'll use by adding .url to our variable name
print(search_results.url)

https://api.crossref.org/works?query.bibliographic=escape+rooms+in+libraries

# Filtering & Select the results

Now with our query variable put together we'll actually search the API and _filter_ our results to:

- Only journal articles, line 7
- One of the authors has an ORCID, line 8 (more on ORCIDs in a bit)

and then we will _select_ only the fields we are interested in. Those are specified in the list on line 2.

In [14]:

select_fields = ['DOI','score','references-count','title','author']
number_of_results = 20

results_for_df = []

for result in search_results.filter(type="journal-article", \
                                    has_orcid="1", \
                                    ).select(select_fields).sample(number_of_results):

                                    print("Retrieved: \n",result)

                                    doi = result['DOI']
                                    score = result['score']
                                    references_count = result['references-count']
                                    title = result['title'][0]

                                    #We will 'try' to get the ORCID of the first listed author
                                    #if that throws an error (except) we'll just leave it blank
                                    #more details on this in a couple of cells
                                    try:
                                      orcid = result['author'][0]['ORCID']
                                    except:
                                      orcid = ""

                                    results_for_df.append([doi,score,references_count,title,orcid])

Retrieved:
 {'DOI': '10.60112/erc.v6.i3.871', 'author': [{'ORCID': 'https://orcid.org/0009-0007-4553-5390', 'authenticated-orcid': False, 'given': 'Juan Carlos', 'family': 'Gómez Jiménez', 'sequence': 'first', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 0, 'score': 20.283777, 'title': ['Escape Rooms educativos y competencias ciudadanas en seguridad vial: revisión crítica del estado del conocimiento', 'Educational Escape Rooms and Civic Competencies in Road Safety: A Critical Review of the State of the Art']}
Retrieved:
 {'DOI': '10.1177/02734753241306093', 'author': [{'ORCID': 'https://orcid.org/0000-0002-6672-6934', 'authenticated-orcid': False, 'given': 'Purvi', 'family': 'Shah', 'sequence': 'first', 'affiliation': [{'name': 'Worcester Polytechnic Institute, MA, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Nandini Ajit', 'family': 'Gadekar', 'sequence': 'additional', 'affiliation': [{'name': 'Worcester Polytechnic Institute, MA, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Steven S.', 'family': 'Taylor', 'sequence': 'additional', 'affiliation': [{'name': 'Worcester Polytechnic Institute, MA, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 139, 'score': 19.28285, 'title': ['Escape From Passive Learning: Harnessing Gamified Digital Educational Escape Rooms for Immersive Marketing Education']}
Retrieved:
 {'DOI': '10.3390/su13084587', 'author': [{'given': 'Agoritsa', 'family': 'Makri', 'sequence': 'first', 'affiliation': [{'name': 'European University Cyprus, 2404 Nicosia, Cyprus'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0002-2033-7343', 'authenticated-orcid': False, 'given': 'Dimitrios', 'family': 'Vlachopoulos', 'sequence': 'additional', 'affiliation': [{'name': 'Amsterdam University of Applied Sciences, 1091 GM Amsterdam, The Netherlands'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Richard A.', 'family': 'Martina', 'sequence': 'additional', 'affiliation': [{'name': 'Amsterdam University of Applied Sciences, 1091 GM Amsterdam, The Netherlands'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 112, 'score': 19.132927, 'title': ['Digital Escape Rooms as Innovative Pedagogical Tools in Education: A Systematic Literature Review']}
Retrieved:
 {'DOI': '10.1021/acs.jchemed.3c00119', 'author': [{'ORCID': 'https://orcid.org/0000-0002-0241-9804', 'authenticated-orcid': True, 'given': 'Aisyah Saad', 'family': 'Abdul Rahim', 'sequence': 'first', 'affiliation': [{'name': 'Department of Pharmacology and Pharmaceutical Chemistry, Faculty of Pharmacy, Universiti Teknologi MARA, Puncak Alam Campus, Bandar Puncak Alam, 42300 Selangor, Malaysia'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 43, 'score': 18.665861, 'title': ['Escape the Desert Island: Blended Escape Rooms in the First-Semester Problem-Based Learning']}
Retrieved:
 {'DOI': '10.1007/s13157-026-02069-0', 'author': [{'ORCID': 'https://orcid.org/0009-0006-8455-7448', 'authenticated-orcid': False, 'given': 'Felix', 'family': 'Klimm', 'sequence': 'first', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Christine', 'family': 'Tamásy', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 54, 'score': 17.831429, 'title': ['Co-creation of Educational Escape Rooms on Paludiculture and Peatlands within a Framework of Transformative Education']}
Retrieved:
 {'DOI': '10.3390/su15097393', 'author': [{'given': 'Tatjana', 'family': 'Sidekerskienė', 'sequence': 'first', 'affiliation': [{'name': 'Department of Applied Mathematics, Kaunas University of Technology, LT-51368 Kaunas, Lithuania'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0001-9990-1084', 'authenticated-orcid': False, 'given': 'Robertas', 'family': 'Damaševičius', 'sequence': 'additional', 'affiliation': [{'name': 'Department of Applied Informatics, Vytautas Magnus University, LT-44404 Kaunas, Lithuania'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 68, 'score': 17.573214, 'title': ['Out-of-the-Box Learning: Digital Escape Rooms as a Metaphor for Breaking Down Barriers in STEM Education']}
Retrieved:
 {'DOI': '10.1108/ijilt-12-2021-0188', 'author': [{'ORCID': 'https://orcid.org/0000-0002-2796-784X', 'authenticated-orcid': False, 'given': 'Robert', 'family': 'Ross', 'sequence': 'first', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Richard', 'family': 'Hall', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0001-7687-6701', 'authenticated-orcid': False, 'given': 'Sarah', 'family': 'Ross', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 22, 'score': 17.516966, 'title': ['Conducting educational escape rooms during a global pandemic']}
Retrieved:
 {'DOI': '10.3390/educsci10090213', 'author': [{'ORCID': 'https://orcid.org/0000-0001-7583-4729', 'authenticated-orcid': False, 'given': 'José Carlos', 'family': 'Piñero Charlo', 'sequence': 'first', 'affiliation': [{'name': 'Department of Didactic of the Mathematics, University of Cadiz, 11510 Cádiz, Spain'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 51, 'score': 17.340046, 'title': ['Educational Escape Rooms as a Tool for Horizontal Mathematization: Learning Process Evidence']}
Retrieved:
 {'DOI': '10.1108/et-10-2024-0474', 'author': [{'ORCID': 'https://orcid.org/0000-0002-1957-2055', 'authenticated-orcid': True, 'given': 'Richard', 'family': 'Martina', 'sequence': 'first', 'affiliation': [{'name': 'Zuyd University of Applied Sciences , ,', 'place': ['Heerlen, Netherlands']}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Kristin', 'family': 'Webb', 'sequence': 'additional', 'affiliation': [{'name': 'Amsterdam University of Applied Sciences , ,', 'place': ['Amsterdam, Netherlands']}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0002-8006-6362', 'authenticated-orcid': True, 'given': 'Ana Katarina', 'family': 'Pessoa-de-Oliveira', 'sequence': 'additional', 'affiliation': [{'name': 'School of Business and Public Management, University of Zaragoza , ,', 'place': ['Zaragoza, Spain']}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 75, 'score': 16.995485, 'title': ['Enhancing social entrepreneurship education through digital educational escape rooms: a literature review']}
Retrieved:
 {'DOI': '10.1002/rev3.70123', 'author': [{'ORCID': 'https://orcid.org/0009-0006-1245-2516', 'authenticated-orcid': False, 'given': 'Chidera Chinedu', 'family': 'Ugo', 'sequence': 'first', 'affiliation': [{'name': 'University of Eastern Finland  Joensuu Finland'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0002-9621-1392', 'authenticated-orcid': False, 'given': 'Sonsoles', 'family': 'López‐Pernas', 'sequence': 'additional', 'affiliation': [{'name': 'University of Eastern Finland  Joensuu Finland'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0001-9785-4827', 'authenticated-orcid': False, 'given': 'Aldo', 'family': 'Gordillo', 'sequence': 'additional', 'affiliation': [{'name': 'Universidad Politécnica de Madrid  Madrid Spain'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0002-8630-5248', 'authenticated-orcid': False, 'given': 'Markku', 'family': 'Tukiainen', 'sequence': 'additional', 'affiliation': [{'name': 'University of Eastern Finland  Joensuu Finland'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 88, 'score': 16.975554, 'title': ['Escape rooms for learning programming: A systematic literature review']}
Retrieved:
 {'DOI': '10.21556/edutec.2025.94.4139', 'author': [{'ORCID': 'https://orcid.org/0000-0002-3767-9497', 'authenticated-orcid': False, 'given': 'Iris Cristina', 'family': 'Peláez Sánchez', 'sequence': 'first', 'affiliation': [], 'role': [{'role': 'author', 'vocabulary': 'crossref'}]}, {'ORCID': 'https://orcid.org/0000-0003-4016-1709', 'authenticated-orcid': False, 'given': 'Gerardo', 'family': 'Rocha Feregrino', 'sequence': 'additional', 'affiliation': [], 'role': [{'role': 'author', 'vocabulary': 'crossref'}]}], 'references-count': 27, 'score': 16.958574, 'title': ['Escape rooms digitales en Spatial y Genially: una intervención para mejorar el engagement académico en estudiantes de ingeniería', 'Digital Escape Rooms in Spatial and Genially: An Intervention to Enhance Academic Engagement among Engineering Students']}
Retrieved:
 {'DOI': '10.1365/s40702-025-01162-y', 'author': [{'ORCID': 'https://orcid.org/0009-0003-3997-8495', 'authenticated-orcid': False, 'given': 'Mirjam', 'family': 'Merkel-Kiss', 'sequence': 'first', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Daniel', 'family': 'Markgraf', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 15, 'score': 16.930586, 'title': ['Förderung der sozialen Integration im Fernstudium durch individualisierte online 3D Escape-Rooms', 'Promoting Social Integration in Distance Learning Through Individualized Online 3D Escape Rooms']}
Retrieved:
 {'DOI': '10.1177/10468781231154596', 'author': [{'ORCID': 'https://orcid.org/0000-0002-9079-278X', 'authenticated-orcid': False, 'given': 'Shawn M.', 'family': 'Doherty', 'sequence': 'first', 'affiliation': [{'name': 'Department of Human Factors and Behavioral Neurobiology, Embry-Riddle Aeronautical University, Daytona Beach, FL, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Andrew C.', 'family': 'Griggs', 'sequence': 'additional', 'affiliation': [{'name': 'Department of Human Factors and Behavioral Neurobiology, Embry-Riddle Aeronautical University, Daytona Beach, FL, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0002-3495-0595', 'authenticated-orcid': False, 'given': 'Elizabeth H.', 'family': 'Lazzara', 'sequence': 'additional', 'affiliation': [{'name': 'Department of Human Factors and Behavioral Neurobiology, Embry-Riddle Aeronautical University, Daytona Beach, FL, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Joseph R.', 'family': 'Keebler', 'sequence': 'additional', 'affiliation': [{'name': 'Department of Human Factors and Behavioral Neurobiology, Embry-Riddle Aeronautical University, Daytona Beach, FL, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Bruce L.', 'family': 'Gewertz', 'sequence': 'additional', 'affiliation': [{'name': 'Department of Surgery, Cedars-Sinai Medical Center, Los Angeles, CA, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0003-2137-6093', 'authenticated-orcid': False, 'given': 'Tara N.', 'family': 'Cohen', 'sequence': 'additional', 'affiliation': [{'name': 'Department of Surgery, Cedars-Sinai Medical Center, Los Angeles, CA, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 36, 'score': 16.904827, 'title': ['Planning an Escape: Considerations for the Development of Applied Escape Rooms']}
Retrieved:
 {'DOI': '10.20448/jeelr.v12i3.6948', 'author': [{'given': 'Maria Valentina Toral', 'family': 'Murillo', 'sequence': 'first', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0009-0001-4080-958X', 'authenticated-orcid': False, 'given': 'Melissa Fernandez', 'family': 'Torres', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0009-0006-7023-0524', 'authenticated-orcid': False, 'given': 'Karen Itzel Mexicano', 'family': 'Muro', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0001-9258-8486', 'authenticated-orcid': False, 'given': 'Elvira Rodriguez', 'family': 'Flores', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 0, 'score': 16.537342, 'title': ['Digital resources and escape rooms: Innovative strategies that improve motivation']}
Retrieved:
 {'DOI': '10.34190/ejel.21.7.3182', 'author': [{'ORCID': 'https://orcid.org/0000-0002-1660-6299', 'authenticated-orcid': False, 'given': 'Rachelle Emily', 'family': 'Rawlinson', 'sequence': 'first', 'affiliation': [], 'role': [{'role': 'author', 'vocabulary': 'crossref'}]}, {'ORCID': 'https://orcid.org/0000-0002-3085-5275', 'authenticated-orcid': False, 'given': 'Nicola', 'family': 'Whitton', 'sequence': 'additional', 'affiliation': [], 'role': [{'role': 'author', 'vocabulary': 'crossref'}]}], 'references-count': 0, 'score': 16.461048, 'title': ['Escape Rooms as Tools for Learning Through Failure']}
Retrieved:
 {'DOI': '10.1128/jmbe.00015-22', 'author': [{'ORCID': 'https://orcid.org/0000-0001-8526-7342', 'authenticated-orcid': True, 'given': 'Ashley B.', 'family': 'Heim', 'sequence': 'first', 'affiliation': [{'name': 'Ecology &amp; Evolutionary Biology, Cornell University, Ithaca, New York, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Jessica', 'family': 'Duke', 'sequence': 'additional', 'affiliation': [{'name': 'School of Biological Sciences, University of Northern Colorado, Greeley, Colorado, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Emily A.', 'family': 'Holt', 'sequence': 'additional', 'affiliation': [{'name': 'School of Biological Sciences, University of Northern Colorado, Greeley, Colorado, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 31, 'score': 16.431479, 'title': ['Design, Discover, and Decipher: Student-Developed Escape Rooms in the Virtual Ecology Classroom']}
Retrieved:
 {'DOI': '10.1080/15505170.2021.1960224', 'author': [{'ORCID': 'https://orcid.org/0000-0001-9100-9091', 'authenticated-orcid': False, 'given': 'Jon', 'family': 'Wargo', 'sequence': 'first', 'affiliation': [{'name': 'Lynch School of Education & Human Development, Boston College, Chestnut Hill, MA, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0002-8417-4723', 'authenticated-orcid': False, 'given': 'Antero', 'family': 'Garcia', 'sequence': 'additional', 'affiliation': [{'name': 'Graduate School of Education, Stanford University, Stanford, CA, USA'}], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 62, 'score': 16.13628, 'title': ['(Re)reading the room: The literacies of escape rooms']}
Retrieved:
 {'DOI': '10.34190/ecgbl.20.2.5434', 'author': [{'given': 'André', 'family': 'Matutat', 'sequence': 'first', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Benjamin', 'family': 'Franke', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0009-0001-7718-6291', 'authenticated-orcid': False, 'given': 'Niklas', 'family': 'Schumann', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'given': 'Hannes', 'family': 'Rüffer', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0009-0001-6148-9677', 'authenticated-orcid': False, 'given': 'Birgit Christina', 'family': 'George', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0002-4230-9060', 'authenticated-orcid': False, 'given': 'Carsten', 'family': 'Gips', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 0, 'score': 16.11146, 'title': ['Building Digital Educational Escape Rooms:  A Modular Toolkit with Low-Code Authoring Approach']}
Retrieved:
 {'DOI': '10.17165/tp.2022.3-4.24-35', 'author': [{'ORCID': 'https://orcid.org/0000-0002-2001-2063', 'authenticated-orcid': False, 'given': 'Elvira', 'family': 'Kovács', 'sequence': 'first', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}, {'ORCID': 'https://orcid.org/0000-0002-8372-2177', 'authenticated-orcid': False, 'given': 'Helena', 'family': 'Manojlovic', 'sequence': 'additional', 'affiliation': [], 'role': [{'vocabulary': 'crossref', 'role': 'author'}]}], 'references-count': 0, 'score': 16.063097, 'title': ['Az oktatási célú szabadulószobák módszertani lehetőségei  egyetemi hallgatóknál', 'Methodological options for educational escape rooms  in university students']}
Retrieved:
 {'DOI': '10.1080/14703297.2025.2602651', 'author': [{'ORCID': 'https://orcid.org/0000-0001-9296-0364', 'authenticated-orcid': False, 'given': 'Emma', 'family': 'Thirkell', 'sequence': 'first', 'affiliation': [{'name': 'Northumbria University', 'place': ['UK']}], 'role': [{'role': 'author', 'vocabulary': 'crossref'}]}], 'references-count': 33, 'score': 15.782223, 'title': ['Designing digital escape rooms for formative assessment: A practical case study in human resource management education']}


# Data to Dataframe

The next cell will turn our retrieved data in a dataframe and display it to the screen.

In [15]:
doi_data = pd.DataFrame(results_for_df,columns=select_fields)
doi_data

,DOI,score,references-count,title,author
0,10.60112/erc.v6.i3.871,20.283777,0,Escape Rooms educativos y competencias ciudada...,https://orcid.org/0009-0007-4553-5390
1,10.1177/02734753241306093,19.282850,139,Escape From Passive Learning: Harnessing Gamif...,https://orcid.org/0000-0002-6672-6934
2,10.3390/su13084587,19.132927,112,Digital Escape Rooms as Innovative Pedagogical...,
3,10.1021/acs.jchemed.3c00119,18.665861,43,Escape the Desert Island: Blended Escape Rooms...,https://orcid.org/0000-0002-0241-9804
4,10.1007/s13157-026-02069-0,17.831429,54,Co-creation of Educational Escape Rooms on Pal...,https://orcid.org/0009-0006-8455-7448
5,10.3390/su15097393,17.573214,68,Out-of-the-Box Learning: Digital Escape Rooms ...,
6,10.1108/ijilt-12-2021-0188,17.516966,22,Conducting educational escape rooms during a g...,https://orcid.org/0000-0002-2796-784X
7,10.3390/educsci10090213,17.340046,51,Educational Escape Rooms as a Tool for Horizon...,https://orcid.org/0000-0001-7583-4729
8,10.1108/et-10-2024-0474,16.995485,75,Enhancing social entrepreneurship education th...,https://orcid.org/0000-0002-1957-2055
9,10.1002/rev3.70123,16.975554,88,Escape rooms for learning programming: A syste...,https://orcid.org/0009-0006-1245-2516
10,10.21556/edutec.2025.94.4139,16.958574,27,Escape rooms digitales en Spatial y Genially: ...,https://orcid.org/0000-0002-3767-9497
11,10.1365/s40702-025-01162-y,16.930586,15,Förderung der sozialen Integration im Fernstud...,https://orcid.org/0009-0003-3997-8495
12,10.1177/10468781231154596,16.904827,36,Planning an Escape: Considerations for the Dev...,https://orcid.org/0000-0002-9079-278X
13,10.20448/jeelr.v12i3.6948,16.537342,0,Digital resources and escape rooms: Innovative...,
14,10.34190/ejel.21.7.3182,16.461048,0,Escape Rooms as Tools for Learning Through Fai...,https://orcid.org/0000-0002-1660-6299
15,10.1128/jmbe.00015-22,16.431479,31,"Design, Discover, and Decipher: Student-Develo...",https://orcid.org/0000-0001-8526-7342
16,10.1080/15505170.2021.1960224,16.136280,62,(Re)reading the room: The literacies of escape...,https://orcid.org/0000-0001-9100-9091
17,10.34190/ecgbl.20.2.5434,16.111460,0,Building Digital Educational Escape Rooms: A ...,
18,10.17165/tp.2022.3-4.24-35,16.063097,0,Az oktatási célú szabadulószobák módszertani l...,https://orcid.org/0000-0002-2001-2063
19,10.1080/14703297.2025.2602651,15.782223,33,Designing digital escape rooms for formative a...,https://orcid.org/0000-0001-9296-0364


#Missing ORCIDs?

Out code is very simple. We are only grabbing the ORCID of the first author that is listed in the item. That author might not have an ORCID. Our search only guaranteed at least one of the authors had and ORCID.

To make life easier we are going to drop any lines in our dataframe that are missing orcids with the following cell

In [16]:
doi_data = doi_data[doi_data['author']!=""]
doi_data

,DOI,score,references-count,title,author
0,10.60112/erc.v6.i3.871,20.283777,0,Escape Rooms educativos y competencias ciudada...,https://orcid.org/0009-0007-4553-5390
1,10.1177/02734753241306093,19.282850,139,Escape From Passive Learning: Harnessing Gamif...,https://orcid.org/0000-0002-6672-6934
3,10.1021/acs.jchemed.3c00119,18.665861,43,Escape the Desert Island: Blended Escape Rooms...,https://orcid.org/0000-0002-0241-9804
4,10.1007/s13157-026-02069-0,17.831429,54,Co-creation of Educational Escape Rooms on Pal...,https://orcid.org/0009-0006-8455-7448
6,10.1108/ijilt-12-2021-0188,17.516966,22,Conducting educational escape rooms during a g...,https://orcid.org/0000-0002-2796-784X
7,10.3390/educsci10090213,17.340046,51,Educational Escape Rooms as a Tool for Horizon...,https://orcid.org/0000-0001-7583-4729
8,10.1108/et-10-2024-0474,16.995485,75,Enhancing social entrepreneurship education th...,https://orcid.org/0000-0002-1957-2055
9,10.1002/rev3.70123,16.975554,88,Escape rooms for learning programming: A syste...,https://orcid.org/0009-0006-1245-2516
10,10.21556/edutec.2025.94.4139,16.958574,27,Escape rooms digitales en Spatial y Genially: ...,https://orcid.org/0000-0002-3767-9497
11,10.1365/s40702-025-01162-y,16.930586,15,Förderung der sozialen Integration im Fernstud...,https://orcid.org/0009-0003-3997-8495
12,10.1177/10468781231154596,16.904827,36,Planning an Escape: Considerations for the Dev...,https://orcid.org/0000-0002-9079-278X
14,10.34190/ejel.21.7.3182,16.461048,0,Escape Rooms as Tools for Learning Through Fai...,https://orcid.org/0000-0002-1660-6299
15,10.1128/jmbe.00015-22,16.431479,31,"Design, Discover, and Decipher: Student-Develo...",https://orcid.org/0000-0001-8526-7342
16,10.1080/15505170.2021.1960224,16.136280,62,(Re)reading the room: The literacies of escape...,https://orcid.org/0000-0001-9100-9091
18,10.17165/tp.2022.3-4.24-35,16.063097,0,Az oktatási célú szabadulószobák módszertani l...,https://orcid.org/0000-0002-2001-2063
19,10.1080/14703297.2025.2602651,15.782223,33,Designing digital escape rooms for formative a...,https://orcid.org/0000-0001-9296-0364

# ORCID Data

You might of heard of ORCID before. It is basically a service that allows a researcher to put a unique serial number on works they publish.

The good news is that ORCID has an API as well. But with this one you need to register ahead of time and get an API key and secret. These basically tell the API who are are when you are using it.

This will require a new library to be installed.

In [17]:
!pip install orcid

import orcid

print("Ready to proceed!")

Collecting orcid
  Downloading orcid-1.0.3.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: html5lib in /usr/local/lib/python3.13/dist-packages (from orcid) (1.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (from orcid) (4.13.5)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from orcid) (2.32.4)
Requirement already satisfied: simplejson in /usr/local/lib/python3.13/dist-packages (from orcid) (4.2.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.13/dist-packages (from orcid) (6.1.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->orcid) (3.0.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->orcid) (4.16.0)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.13/dist-packages (from html5lib->orcid) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.13/dist-packages (from html5lib->orcid) (0.6.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->orcid) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->orcid) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->orcid) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->orcid) (2026.7.22)
Building wheels for collected packages: orcid
  Building wheel for orcid (setup.py) ... done
  Created wheel for orcid: filename=orcid-1.0.3-py3-none-any.whl size=10522 sha256=576e6ad8778e7d0eab052f2736367ca814c7e238c02301043d46dbfbb4b3362d
  Stored in directory: /root/.cache/pip/wheels/27/62/60/1dfc75d4ba78ed74709f714a5bca25cff4ad81e764bb0db2b9
Successfully built orcid
Installing collected packages: orcid
Successfully installed orcid-1.0.3
Ready to proceed!


# API again, but with more information

We need to register with the ORCID API before we use it. We need to get an API ID and Secret ([details here](https://info.orcid.org/what-is-orcid/services/public-api/)).

When you generate them simply fill in these details in line 2 and 3. If you are having trouble with this please get in touch with me and I can help you with that process.

In [18]:
# Our Info from the ORCID site
Client_ID = "APP-RMZKOKCT6F983QP1"
Client_Secret = "926a14a6-fee5-4fd0-8e57-2044c6135982"

#with that set we do our Python API work...
orcid_api = api = orcid.PublicAPI(Client_ID, Client_Secret, sandbox=False)
search_token = api.get_search_token_from_orcid()


# Grabbing Info

We can now grab information about an ORCID. Run the next cell to see the [works](https://orcid.org/0000-0001-9229-8569#works) I've produced.

In [19]:
orcid_results = orcid_api.read_record_public("0000-0001-9229-8569",'works', search_token)
orcid_results

{'last-modified-date': {'value': 1789043153699},
 'group': [{'last-modified-date': {'value': 1789043153699},
   'external-ids': {'external-id': [{'external-id-type': 'doi',
      'external-id-value': '10.31274/jlsc.21406',
      'external-id-url': {'value': 'https://doi.org/10.31274/jlsc.21406'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 226263248,
     'created-date': {'value': 1789001603154},
     'last-modified-date': {'value': 1789043153699},
     'source': {'source-orcid': None,
      'source-client-id': {'uri': 'http://orcid.org/client/0000-0001-9884-1913',
       'path': '0000-0001-9884-1913',
       'host': 'orcid.org'},
      'source-name': {'value': 'Crossref'}},
     'title': {'title': {'value': 'Constructing a (Meaningful) Scholarly Publishing Narrative: Bootstrapping Green Open Access Submissions for Open Access Week'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.31274/jlsc.21406',
        'external-id-url': {'value': 'https://doi.org/10.31274/jlsc.21406'},
        'external-id-relationship': 'SELF'}]},
     'type': 'JOURNAL_ARTICLE',
     'publication-date': {'year': {'value': '2026'},
      'month': {'value': '09'},
      'day': {'value': '10'},
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/226263248',
     'display-index': '1'}]},
  {'last-modified-date': {'value': 1781192213886},
   'external-ids': {'external-id': [{'external-id-type': 'doi',
      'external-id-value': '10.1353/lib.2026.a992002',
      'external-id-url': {'value': 'https://doi.org/10.1353/lib.2026.a992002'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 217416893,
     'created-date': {'value': 1781192209342},
     'last-modified-date': {'value': 1781192213886},
     'source': {'source-orcid': {'uri': 'http://orcid.org/0000-0001-9229-8569',
       'path': '0000-0001-9229-8569',
       'host': 'orcid.org'},
      'source-client-id': None,
      'source-name': {'value': 'Tim Ribaric'}},
     'title': {'title': {'value': 'Skeptically Defining the “Post-Reference Epoch”'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.1353/lib.2026.a992002',
        'external-id-url': {'value': 'https://doi.org/10.1353/lib.2026.a992002'},
        'external-id-relationship': 'SELF'},
       {'external-id-type': 'issn',
        'external-id-value': '1559-0682',
        'external-id-url': {'value': 'https://portal.issn.org/resource/ISSN/1559-0682'},
        'external-id-relationship': 'PART_OF'}]},
     'type': 'JOURNAL_ARTICLE',
     'publication-date': {'year': {'value': '2026'},
      'month': {'value': '05'},
      'day': None,
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/217416893',
     'display-index': '0'}]},
  {'last-modified-date': {'value': 1743431282519},
   'external-ids': {'external-id': [{'external-id-type': 'doi',
      'external-id-value': '10.58188/1941-8043.1920',
      'external-id-url': {'value': 'https://doi.org/10.58188/1941-8043.1920'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 181263774,
     'created-date': {'value': 1743431282519},
     'last-modified-date': {'value': 1743431282519},
     'source': {'source-orcid': {'uri': 'http://orcid.org/0000-0001-9229-8569',
       'path': '0000-0001-9229-8569',
       'host': 'orcid.org'},
      'source-client-id': None,
      'source-name': {'value': 'Tim Ribaric'}},
     'title': {'title': {'value': 'How Do Collective Agreements Stack Up? Implications For Academic Freedom'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.58188/1941-8043.1920',
        'external-id-url': {'value': 'https://doi.org/10.58188/1941-8043.1920'},
        'external-id-relationship': 'SELF'},
       {'external-id-type': 'issn',
        'external-id-value': '1941-8043',
        'external-id-url': {'value': 'https://portal.issn.org/resource/ISSN/1941-8043'},
        'external-id-relationship': 'PART_OF'}]},
     'type': 'JOURNAL_ARTICLE',
     'publication-date': {'year': {'value': '2025'},
      'month': {'value': '03'},
      'day': {'value': '25'},
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/181263774',
     'display-index': '0'}]},
  {'last-modified-date': {'value': 1741886100128},
   'external-ids': {'external-id': [{'external-id-type': 'doi',
      'external-id-value': '10.33137/cjal-rcbu.v11.44650',
      'external-id-url': {'value': 'https://doi.org/10.33137/cjal-rcbu.v11.44650'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 179987394,
     'created-date': {'value': 1741883146122},
     'last-modified-date': {'value': 1741886100128},
     'source': {'source-orcid': None,
      'source-client-id': {'uri': 'http://orcid.org/client/APP-WRYD6WNYYH3PPEMZ',
       'path': 'APP-WRYD6WNYYH3PPEMZ',
       'host': 'orcid.org'},
      'source-name': {'value': 'University of Toronto Libraries'}},
     'title': {'title': {'value': 'Academic Librarianship in Canada: Post-COVID Perspectives in a Neoliberal Era, edited by Jessica E. Shiers, Harriet M. Sonne de Torrens, Joanna Szurmak, and Meaghan Valant'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.33137/cjal-rcbu.v11.44650',
        'external-id-url': {'value': 'https://doi.org/10.33137/cjal-rcbu.v11.44650'},
        'external-id-relationship': 'SELF'},
       {'external-id-type': 'issn',
        'external-id-value': '2369-937X',
        'external-id-url': None,
        'external-id-relationship': 'PART_OF'}]},
     'type': 'JOURNAL_ARTICLE',
     'publication-date': {'year': {'value': '2025'},
      'month': {'value': '03'},
      'day': {'value': '13'},
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/179987394',
     'display-index': '1'},
    {'put-code': 179990071,
     'created-date': {'value': 1741885132368},
     'last-modified-date': {'value': 1741886100128},
     'source': {'source-orcid': None,
      'source-client-id': {'uri': 'http://orcid.org/client/0000-0001-9884-1913',
       'path': '0000-0001-9884-1913',
       'host': 'orcid.org'},
      'source-name': {'value': 'Crossref'}},
     'title': {'title': {'value': 'Academic Librarianship in Canada: Post-COVID Perspectives in a Neoliberal Era, edited by Jessica E. Shiers, Harriet M. Sonne de Torrens, Joanna Szurmak, and Meaghan Valant'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.33137/cjal-rcbu.v11.44650',
        'external-id-url': {'value': 'https://doi.org/10.33137/cjal-rcbu.v11.44650'},
        'external-id-relationship': 'SELF'}]},
     'type': 'JOURNAL_ARTICLE',
     'publication-date': {'year': {'value': '2025'},
      'month': {'value': '03'},
      'day': {'value': '13'},
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/179990071',
     'display-index': '1'}]},
  {'last-modified-date': {'value': 1743094895050},
   'external-ids': {'external-id': [{'external-id-type': 'doi',
      'external-id-value': '10.63409/2024.49',
      'external-id-url': {'value': 'https://doi.org/10.63409/2024.49'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 180839904,
     'created-date': {'value': 1742913926675},
     'last-modified-date': {'value': 1743094895050},
     'source': {'source-orcid': None,
      'source-client-id': {'uri': 'http://orcid.org/client/0000-0001-9884-1913',
       'path': '0000-0001-9884-1913',
       'host': 'orcid.org'},
      'source-name': {'value': 'Crossref'}},
     'title': {'title': {'value': 'Life at the table'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.63409/2024.49',
        'external-id-url': {'value': 'https://doi.org/10.63409/2024.49'},
        'external-id-relationship': 'SELF'}]},
     'type': 'JOURNAL_ARTICLE',
     'publication-date': {'year': {'value': '2024'},
      'month': {'value': '12'},
      'day': {'value': '20'},
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/180839904',
     'display-index': '1'}]},
  {'last-modified-date': {'value': 1711650744738},
   'external-ids': {'external-id': [{'external-id-type': 'doi',
      'external-id-value': '10.3138/cjc-2023-0003',
      'external-id-url': {'value': 'https://doi.org/10.3138/cjc-2023-0003'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 156495201,
     'created-date': {'value': 1711650744738},
     'last-modified-date': {'value': 1711650744738},
     'source': {'source-orcid': {'uri': 'http://orcid.org/0000-0001-9229-8569',
       'path': '0000-0001-9229-8569',
       'host': 'orcid.org'},
      'source-client-id': None,
      'source-name': {'value': 'Tim Ribaric'}},
     'title': {'title': {'value': 'The Role of Municipalities in Communicating for Community Resilience during the COVID-19 Pandemic: A Study of Niagara Region’s Crisis Communication'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.3138/cjc-2023-0003',
        'external-id-url': {'value': 'https://doi.org/10.3138/cjc-2023-0003'},
        'external-id-relationship': 'SELF'},
       {'external-id-type': 'issn',
        'external-id-value': '0705-3657',
        'external-id-url': {'value': 'https://portal.issn.org/resource/ISSN/0705-3657'},
        'external-id-relationship': 'PART_OF'},
       {'external-id-type': 'issn',
        'external-id-value': '1499-6642',
        'external-id-url': {'value': 'https://portal.issn.org/resource/ISSN/1499-6642'},
        'external-id-relationship': 'PART_OF'}]},
     'type': 'JOURNAL_ARTICLE',
     'publication-date': {'year': {'value': '2024'},
      'month': {'value': '03'},
      'day': {'value': '01'},
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/156495201',
     'display-index': '1'}]},
  {'last-modified-date': {'value': 1709565543433},
   'external-ids': {'external-id': [{'external-id-type': 'doi',
      'external-id-value': '10.24908/ss.v22i1.16847',
      'external-id-url': {'value': 'https://doi.org/10.24908/ss.v22i1.16847'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 154397538,
     'created-date': {'value': 1709272429265},
     'last-modified-date': {'value': 1709565543433},
     'source': {'source-orcid': None,
      'source-client-id': {'uri': 'http://orcid.org/client/0000-0001-9884-1913',
       'path': '0000-0001-9884-1913',
       'host': 'orcid.org'},
      'source-name': {'value': 'Crossref'}},
     'title': {'title': {'value': 'Review of Doctorow’s The Internet Con: How to Seize the Means of Computation'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.24908/ss.v22i1.16847',
        'external-id-url': {'value': 'https://doi.org/10.24908/ss.v22i1.16847'},
        'external-id-relationship': 'SELF'}]},
     'type': 'JOURNAL_ARTICLE',
     'publication-date': {'year': {'value': '2024'},
      'month': {'value': '02'},
      'day': {'value': '29'},
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/154397538',
     'display-index': '0'}]},
  {'last-modified-date': {'value': 1729196228224},
   'external-ids': {'external-id': [{'external-id-type': 'doi',
      'external-id-value': '10.5683/SP3/P5TPTE',
      'external-id-url': {'value': 'https://doi.org/10.5683/SP3/P5TPTE'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 169792538,
     'created-date': {'value': 1729196221444},
     'last-modified-date': {'value': 1729196228224},
     'source': {'source-orcid': {'uri': 'http://orcid.org/0000-0001-9229-8569',
       'path': '0000-0001-9229-8569',
       'host': 'orcid.org'},
      'source-client-id': None,
      'source-name': {'value': 'Tim Ribaric'}},
     'title': {'title': {'value': 'PSE policies Canada (July 2024)'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.5683/SP3/P5TPTE',
        'external-id-url': {'value': 'https://doi.org/10.5683/SP3/P5TPTE'},
        'external-id-relationship': 'SELF'}]},
     'type': 'DATA_SET',
     'publication-date': {'year': {'value': '2024'},
      'month': None,
      'day': None,
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/169792538',
     'display-index': '0'}]},
  {'last-modified-date': {'value': 1688041858085},
   'external-ids': {'external-id': [{'external-id-type': 'doi',
      'external-id-value': '10.5334/johd.109',
      'external-id-url': {'value': 'https://doi.org/10.5334/johd.109'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 137750869,
     'created-date': {'value': 1688037213834},
     'last-modified-date': {'value': 1688041858085},
     'source': {'source-orcid': None,
      'source-client-id': {'uri': 'http://orcid.org/client/0000-0001-9884-1913',
       'path': '0000-0001-9884-1913',
       'host': 'orcid.org'},
      'source-name': {'value': 'Crossref'}},
     'title': {'title': {'value': 'A Mixed Method Twitter Methodology and Anonymous Corpus'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.5334/johd.109',
        'external-id-url': {'value': 'https://doi.org/10.5334/johd.109'},
        'external-id-relationship': 'SELF'}]},
     'type': 'JOURNAL_ARTICLE',
     'publication-date': {'year': {'value': '2023'},
      'month': {'value': '06'},
      'day': {'value': '29'},
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/137750869',
     'display-index': '0'}]},
  {'last-modified-date': {'value': 1678474154483},
   'external-ids': {'external-id': [{'external-id-type': 'doi',
      'external-id-value': '10.33137/cjal-rcbu.v9.39661',
      'external-id-url': {'value': 'https://doi.org/10.33137/cjal-rcbu.v9.39661'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 130130964,
     'created-date': {'value': 1677870994209},
     'last-modified-date': {'value': 1678474154483},
     'source': {'source-orcid': None,
      'source-client-id': {'uri': 'http://orcid.org/client/0000-0001-9884-1913',
       'path': '0000-0001-9884-1913',
       'host': 'orcid.org'},
      'source-name': {'value': 'Crossref'}},
     'title': {'title': {'value': 'Data Cartels, by Sarah Lamdan'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.33137/cjal-rcbu.v9.39661',
        'external-id-url': {'value': 'https://doi.org/10.33137/cjal-rcbu.v9.39661'},
        'external-id-relationship': 'SELF'}]},
     'type': 'JOURNAL_ARTICLE',
     'publication-date': {'year': {'value': '2023'},
      'month': {'value': '03'},
      'day': {'value': '03'},
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/130130964',
     'display-index': '0'}]},
  {'last-modified-date': {'value': 1673372094053},
   'external-ids': {'external-id': [{'external-id-type': 'doi',
      'external-id-value': '10.33137/cjal-rcbu.v8.38423',
      'external-id-url': {'value': 'https://doi.org/10.33137/cjal-rcbu.v8.38423'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 126210499,
     'created-date': {'value': 1673372094053},
     'last-modified-date': {'value': 1673372094053},
     'source': {'source-orcid': {'uri': 'http://orcid.org/0000-0001-9229-8569',
       'path': '0000-0001-9229-8569',
       'host': 'orcid.org'},
      'source-client-id': None,
      'source-name': {'value': 'Tim Ribaric'}},
     'title': {'title': {'value': 'No Justice, Only Struggle'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.33137/cjal-rcbu.v8.38423',
        'external-id-url': {'value': 'https://doi.org/10.33137/cjal-rcbu.v8.38423'},
        'external-id-relationship': 'SELF'},
       {'external-id-type': 'issn',
        'external-id-value': '2369-937X',
        'external-id-url': {'value': 'https://portal.issn.org/resource/ISSN/2369-937X'},
        'external-id-relationship': 'PART_OF'}]},
     'type': 'JOURNAL_ARTICLE',
     'publication-date': {'year': {'value': '2023'},
      'month': {'value': '01'},
      'day': {'value': '09'},
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/126210499',
     'display-index': '1'}]},
  {'last-modified-date': {'value': 1665505260521},
   'external-ids': {'external-id': [{'external-id-type': 'doi',
      'external-id-value': '10.4324/9781003159155-8',
      'external-id-url': {'value': 'https://doi.org/10.4324/9781003159155-8'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 120565195,
     'created-date': {'value': 1665504208072},
     'last-modified-date': {'value': 1665505260521},
     'source': {'source-orcid': None,
      'source-client-id': {'uri': 'http://orcid.org/client/0000-0001-9884-1913',
       'path': '0000-0001-9884-1913',
       'host': 'orcid.org'},
      'source-name': {'value': 'Crossref'}},
     'title': {'title': {'value': '“Put the fucking salary in the job ad!”'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'doi',
        'external-id-value': '10.4324/9781003159155-8',
        'external-id-url': {'value': 'https://doi.org/10.4324/9781003159155-8'},
        'external-id-relationship': 'SELF'}]},
     'type': 'BOOK_CHAPTER',
     'publication-date': {'year': {'value': '2022'},
      'month': {'value': '10'},
      'day': {'value': '11'},
      'media-type': None},
     'visibility': 'PUBLIC',
     'path': '/0000-0001-9229-8569/work/120565195',
     'display-index': '0'}]},
  {'last-modified-date': {'value': 1672858499617},
   'external-ids': {'external-id': [{'external-id-type': 'handle',
      'external-id-value': '10464/15769',
      'external-id-url': {'value': 'http://hdl.handle.net/10464/15769'},
      'external-id-relationship': 'SELF'}]},
   'work-summary': [{'put-code': 125827112,
     'created-date': {'value': 1672858499617},
     'last-modified-date': {'value': 1672858499617},
     'source': {'source-orcid': {'uri': 'http://orcid.org/0000-0001-9229-8569',
       'path': '0000-0001-9229-8569',
       'host': 'orcid.org'},
      'source-client-id': None,
      'source-name': {'value': 'Tim Ribaric'}},
     'title': {'title': {'value': 'Data Analysis as the Next Step'},
      'subtitle': None,
      'translated-title': None},
     'external-ids': {'external-id': [{'external-id-type': 'handle',
        'external-id-value': '10464/15769',
        'external-id-url': {'value': 'http://hdl.handle.net/10464/15769'},
        'external-id-relationship': 'SELF'}]},
     'type': 'JOURNAL_ARTICLE',
     'publication-date': {'year': {'value': '2022'},
      'month': {'value': '06'},
      'day': {'value': '01'},
      'media-type': None},

#JSON overload!

That's a lot of JSON to look at. What we are going to focus on is just grabbing the number of _Works_ each author has published and use that value in our analysis.

In [20]:
#The number of works I've published
len(orcid_results['group'])

28


# Filling our dataset

Now we are going to put all of this together!

We are going to use the ORCID API to find out how many things each first author has published and then we are going to add this to our dataframe!

Why? You'll see soon.

In [21]:
authors = doi_data['author'].to_list()
author_works_count = []

for a in authors:
  author_orcid = a.split('/')[-1]
  print("Working on",a)
  orcid_results = orcid_api.read_record_public(author_orcid,'works', search_token)
  count = len(orcid_results['group'])
  print("Found ", count, "works")
  author_works_count.append(count)

Working on https://orcid.org/0009-0007-4553-5390
Found  0 works
Working on https://orcid.org/0000-0002-6672-6934
Found  23 works
Working on https://orcid.org/0000-0002-0241-9804
Found  55 works
Working on https://orcid.org/0009-0006-8455-7448
Found  0 works
Working on https://orcid.org/0000-0002-2796-784X
Found  27 works
Working on https://orcid.org/0000-0001-7583-4729
Found  67 works
Working on https://orcid.org/0000-0002-1957-2055
Found  4 works
Working on https://orcid.org/0009-0006-1245-2516
Found  2 works
Working on https://orcid.org/0000-0002-3767-9497
Found  25 works
Working on https://orcid.org/0009-0003-3997-8495
Found  3 works
Working on https://orcid.org/0000-0002-9079-278X
Found  4 works
Working on https://orcid.org/0000-0002-1660-6299
Found  9 works
Working on https://orcid.org/0000-0001-8526-7342
Found  46 works
Working on https://orcid.org/0000-0001-9100-9091
Found  35 works
Working on https://orcid.org/0000-0002-2001-2063
Found  75 works
Working on https://orcid.org/0000-0001-9296-0364
Found  4 works


# Augmenting our Dataframe

Now that we have this information, we'll add it as another column in our dataframe. This cell might throw a _warning_ but that is safe to ignore.

In [22]:
#Now we add this list as a column to our Dataframe
doi_data['author_work_count'] = author_works_count
doi_data

/tmp/ipykernel_1610/2190627056.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  doi_data['author_work_count'] = author_works_count

,DOI,score,references-count,title,author,author_work_count
0,10.60112/erc.v6.i3.871,20.283777,0,Escape Rooms educativos y competencias ciudada...,https://orcid.org/0009-0007-4553-5390,0
1,10.1177/02734753241306093,19.282850,139,Escape From Passive Learning: Harnessing Gamif...,https://orcid.org/0000-0002-6672-6934,23
3,10.1021/acs.jchemed.3c00119,18.665861,43,Escape the Desert Island: Blended Escape Rooms...,https://orcid.org/0000-0002-0241-9804,55
4,10.1007/s13157-026-02069-0,17.831429,54,Co-creation of Educational Escape Rooms on Pal...,https://orcid.org/0009-0006-8455-7448,0
6,10.1108/ijilt-12-2021-0188,17.516966,22,Conducting educational escape rooms during a g...,https://orcid.org/0000-0002-2796-784X,27
7,10.3390/educsci10090213,17.340046,51,Educational Escape Rooms as a Tool for Horizon...,https://orcid.org/0000-0001-7583-4729,67
8,10.1108/et-10-2024-0474,16.995485,75,Enhancing social entrepreneurship education th...,https://orcid.org/0000-0002-1957-2055,4
9,10.1002/rev3.70123,16.975554,88,Escape rooms for learning programming: A syste...,https://orcid.org/0009-0006-1245-2516,2
10,10.21556/edutec.2025.94.4139,16.958574,27,Escape rooms digitales en Spatial y Genially: ...,https://orcid.org/0000-0002-3767-9497,25
11,10.1365/s40702-025-01162-y,16.930586,15,Förderung der sozialen Integration im Fernstud...,https://orcid.org/0009-0003-3997-8495,3
12,10.1177/10468781231154596,16.904827,36,Planning an Escape: Considerations for the Dev...,https://orcid.org/0000-0002-9079-278X,4
14,10.34190/ejel.21.7.3182,16.461048,0,Escape Rooms as Tools for Learning Through Fai...,https://orcid.org/0000-0002-1660-6299,9
15,10.1128/jmbe.00015-22,16.431479,31,"Design, Discover, and Decipher: Student-Develo...",https://orcid.org/0000-0001-8526-7342,46
16,10.1080/15505170.2021.1960224,16.136280,62,(Re)reading the room: The literacies of escape...,https://orcid.org/0000-0001-9100-9091,35
18,10.17165/tp.2022.3-4.24-35,16.063097,0,Az oktatási célú szabadulószobák módszertani l...,https://orcid.org/0000-0002-2001-2063,75
19,10.1080/14703297.2025.2602651,15.782223,33,Designing digital escape rooms for formative a...,https://orcid.org/0000-0001-9296-0364,4


# The Grand Finale!

We are going to now make a correlation matrix to see what relationship there is between score, number of references, and the number of works the author has completed!

In [23]:
#Lot going on here... Just run this cell and look at the final product to answer the next question
corr = doi_data.corr(numeric_only=True)
corr.style.background_gradient(cmap='coolwarm')
mask = np.zeros_like(corr, dtype=bool)
mask[np.triu_indices_from(mask)] = True
corr[mask] = np.nan
(corr
 .style
 .background_gradient(cmap='coolwarm', axis=None, vmin=-1, vmax=1)
 .highlight_null(color='#f1f1f1')  # Color NaNs grey
 )


# Congrats on doing Data Science

I'll let you decide what to think of the results from the correlation matrix.

Remember
- -1 is strong negative correlation, eg. One goes up the other always goes down.
- 0 means no correspondence between the two variables
- 1 a strong positive correlation, eg. One goes up the other always goes up too.


# Saving our new dataset!

We've spent some time creating a nice dataset from a few different sources so let's take the time to save it as a CSV file. Like we did in the warm-up we'll connect to Google Drive and save our file in our usual folder.

In [ ]:
#This will automatically download the file
#please check your downloads directory for it.
from google.colab import drive
drive.mount('/content/gdrive')
doi_data.to_csv('adv_week2_doi_dataset.csv',index=False)

#This next line copies (cp) the csv file from our working folder
#to the special folder we've created for our work
!cp adv_week2_doi_dataset.csv /content/gdrive/MyDrive/LibraryJuicePython

print("File copied to Drive!")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
File copied to Drive!


# Questions for this Workalong

You'll notice there is a lack of questions in this workalong. I'm going to ask you now to head up to the section called **Searching the API** and change the search query to something you are interested in and re-run the subsequent cells to create a dataset on a different topic. Feel free to also adjust `number_of_results` to a number larger than 20 to make a bigger dataset (but don't go too big with it, certainly keep in under 50)

Be sure to save the CSV file of the final dataset in Google Drive. We'll be using it again later.